### ISSUE TITLE
Data scrapping

### ISSUE THREAD

**Issue by andreivreja** [jessinthecloud/new-world#1]
Hey there,

If you’re planning to scrape data from nwdb.info, I’d appreciate getting in touch first. Especially if you’re considering open sourcing the scrapping part itself.

**Comment by ebuwiz** [comment]
You can add a Language selector??? Builds are easy to translate, will help a lot of people.

**Comment by jessinthecloud** [comment]
I'm not, but will certainly reach out if the need arises. andyfr#5012's spreadsheet is pretty much the goal and contains all the necessary data, plus no point in recreating a database that someone else already does very well :) 
Though simple curl requests are definitely not a secret art haha

**Comment by jessinthecloud** [comment]
@andreivreja Apologies, I forgot about the JS snippet. While not scraped, I did poke around the tooltip because frankly it's cool as hell and JS is essentially magic that I want to someday understand more about. I'll remove that
